apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: admin-credentials
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend-global
    kind: ClusterSecretStore
  target:
    name: admin-credentials
  data:
  - secretKey: username
    remoteRef:
      key: infrastructure/global/monitoring-stack/grafana
      property: username

  - secretKey: password
    remoteRef:
      key: infrastructure/global/monitoring-stack/grafana
      property: password
