apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: kube-prometheus-stack-crs
  namespace: flux-system
spec:
  interval: 10m
  retryInterval: 1m
  path: ./deploy/kube-prometheus-stack/crs
  prune: true
  sourceRef:
    kind: GitRepository
    name: monitoring-stack
