apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: flux-system
spec:
  # Override Release name to avoid the pattern Namespace-Release
  # Ref: https://fluxcd.io/docs/components/helm/api/#helm.toolkit.fluxcd.io/v2beta1.HelmRelease
  releaseName: kube-prometheus-stack
  targetNamespace: kube-prometheus-stack
  interval: 5m
  chart:
    spec:
      chart: ./deploy/kube-prometheus-stack/operator
      sourceRef:
        kind: GitRepository
        name: monitoring-stack
        namespace: flux-system
      valuesFiles:
        - ./deploy/kube-prometheus-stack/operator/values.yaml

  # Ref: https://fluxcd.io/docs/components/helm/api/#helm.toolkit.fluxcd.io/v2beta1.Install
  install:
    createNamespace: true
    remediation: &remediation
      retries: 10
      remediateLastFailure: true
  upgrade:
    remediation: *remediation
