apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: grafana-crs
  namespace: flux-system
spec:
  interval: 10m
  retryInterval: 1m
  path: ./deploy/grafana/crs
  prune: true
  sourceRef:
    kind: GitRepository
    name: monitoring-stack
