apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-templates
data:
  template_slack.tmpl: |
    # Define the silence URL
    {{ define "__alert_silence_link" -}}
      {{ .ExternalURL }}/#/silences/new?filter=%7B
      {{- range .CommonLabels.SortedPairs -}}
          {{- if ne .Name "alertname" -}}
              {{- .Name }}%3D"{{- .Value | urlquery -}}"%2C%20
          {{- end -}}
      {{- end -}}
      alertname%3D"{{- .CommonLabels.alertname -}}"%7D
    {{- end }}

    # Define alert severity variable
    {{ define "__alert_severity" -}}
      {{- if eq .CommonLabels.severity "critical" -}}
      *Severity:* 'Critical'
      {{- else if eq .CommonLabels.severity "warning" -}}
      *Severity:* 'Warning'
      {{- else if eq .CommonLabels.severity "info" -}}
      *Severity:* 'Info'
      {{- else -}}
      *Severity:* :question: {{ .CommonLabels.severity }}
      {{- end }}
    {{- end }}

    # Define Slack title
    {{ define "slack.title" -}}
    [{{ .Status | toUpper -}}
    {{ if eq .Status "firing" }} <{{ .Alerts.Firing | len }}>{{- end -}}
    ] {{ .CommonLabels.alertname }}
    {{- end }}

    # Define Slack text
    {{ define "slack.text" -}}
      {{ template "__alert_severity" . }}
      {{- if (index .Alerts 0).Annotations.summary }}
      {{- "\n" -}}
      *Summary:* {{ (index .Alerts 0).Annotations.summary }}
      {{- end }}
      {{ range .Alerts }}
          {{- if .Annotations.description }}
          {{- "\n" -}}
          {{ .Annotations.description }}
          {{- "\n" -}}
          {{- end }}
          {{- if .Annotations.message }}
          {{- "\n" -}}
          {{ .Annotations.message }}
          {{- "\n" -}}
          {{- end }}
      {{- end }}
    {{- end }}

    # Define Slack message color based on severity level
    {{ define "slack.color" -}}
      {{ if eq .Status "firing" -}}
          {{ if eq .CommonLabels.severity "warning" -}}
              warning
          {{- else if eq .CommonLabels.severity "critical" -}}
              danger
          {{- else -}}
              #439FE0
          {{- end -}}
      {{ else -}}
      good
      {{- end }}
    {{- end }}
