apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: alertmanager-global-notifications-slack
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend-global
    kind: ClusterSecretStore
  target:
    name: alertmanager-global-notifications-slack
  data:
  - secretKey: apiURL
    remoteRef:
      key: infrastructure/global/monitoring-stack/kube-prometheus-stack/alertmanager
      property: slack-webhook
