apiVersion: replika.prosimcorp.com/v1alpha1
kind: Replika
metadata:
  name: global-notifications-secret
spec:
  # Some configuration features
  synchronization:
    time: "20s"

  # Defines the resource to sync through namespaces
  source:
    group: ""
    version: v1
    kind: Secret
    name: alertmanager-global-notifications-slack
    namespace: &sourceNamespace kube-prometheus-stack

  # Defines the resources that will be generated
  target:
    namespaces:
      matchAll: true
      excludeFrom:
        - *sourceNamespace
